### ISSUE TITLE
启动 munchkin后报错

### ISSUE THREAD

**Issue by controZheng** [WeOps-Lab/OpsPilot#69]
<img width="1099" alt="image" src="https://github.com/user-attachments/assets/f843d479-3c75-4b9d-95fb-cf5e5ebb4ee6">

Executing consistency checks...
2024-07-29 03:26:15.348 | DEBUG    | munchkin.urls:<module>:78 - 加载[apps.core]的路由......
2024-07-29 03:26:15.375 | DEBUG    | munchkin.urls:<module>:78 - 加载[apps.model_provider_mgmt]的路由......
2024-07-29 03:26:15.381 | DEBUG    | munchkin.urls:<module>:78 - 加载[apps.knowledge_mgmt]的路由......
2024-07-29 03:26:15.385 | DEBUG    | munchkin.urls:<module>:78 - 加载[apps.channel_mgmt]的路由......
2024-07-29 03:26:15.387 | DEBUG    | munchkin.urls:<module>:78 - 加载[apps.bot_mgmt]的路由......
2024-07-29 03:26:15.483 | INFO     | apps.bot_mgmt.management.commands.consume_bot_event:handle:89 - 初始化消息队列连接:[rabbitmq-service:5672]
Traceback (most recent call last):
  File "/apps/manage.py", line 22, in <module>
    main()
  File "/apps/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/apps/apps/bot_mgmt/management/commands/consume_bot_event.py", line 99, in handle
    channel.basic_consume("pilot", on_message)
  File "/usr/local/lib/python3.10/dist-packages/pika/adapters/blocking_connection.py", line 1645, in basic_consume
    return self._basic_consume_impl(
  File "/usr/local/lib/python3.10/dist-packages/pika/adapters/blocking_connection.py", line 1714, in _basic_consume_impl
    self._flush_output(ok_result.is_ready)
  File "/usr/local/lib/python3.10/dist-packages/pika/adapters/blocking_connection.py", line 1357, in _flush_output
    raise self._closing_reason  # pylint: disable=E0702
pika.exceptions.ChannelClosedByBroker: (404, "NOT_FOUND - no queue 'pilot' in vhost '/'")
2024-07-29 03:26:16,055 INFO exited: conversation (exit status 1; not expected)

**Comment by etherfurnace** [comment]
这是一个conversation服务，负责从队列获取对话记录的，有pilot就好了~，优化会在3.0的时候一并优化
